export const CREATE_DEPARTMENT_TYPE = "CREATE_DEPARTMENT_TYPE";
export const GET_DEPARTMENT_TYPE = "GET_DEPARTMENT_TYPE";
export const UPDATE_DEPARTMENT_TYPE = "UPDATE_DEPARTMENT_TYPE";
export const DELETE_DEPARTMENT_TYPE = "DELETE_DEPARTMENT_TYPE";

export const CREATE_POSITION_TYPE = "CREATE_POSITION_TYPE";
export const GET_POSITION_TYPE = "GET_POSITION_TYPE";
export const UPDATE_POSITION_TYPE = "UPDATE_POSITION_TYPE";
export const DELETE_POSITION_TYPE = "DELETE_POSITION_TYPE";

export const CREATE_POSITION_STATUS = "CREATE_POSITION_STATUS";
export const GET_POSITION_STATUS = "GET_POSITION_STATUS";
export const UPDATE_POSITION_STATUS = "UPDATE_POSITION_STATUS";
export const DELETE_POSITION_STATUS = "DELETE_POSITION_STATUS";

export const CREATE_WORKING_HOUR = "CREATE_WORKING_HOUR";
export const GET_WORKING_HOUR = "GET_WORKING_HOUR";
export const UPDATE_WORKING_HOUR = "UPDATE_WORKING_HOUR";
export const DELETE_WORKING_HOUR = "DELETE_WORKING_HOUR";

export const CREATE_WORKING_PLACE = "CREATE_WORKING_PLACE";
export const GET_WORKING_PLACE = "GET_WORKING_PLACE";
export const UPDATE_WORKING_PLACE = "UPDATE_WORKING_PLACE";
export const DELETE_WORKING_PLACE = "DELETE_WORKING_PLACE";

export const CREATE_MANPOWER_REQUISITION = "CREATE_MANPOWER_REQUISITION";
export const GET_MANPOWER_REQUISITION = "GET_MANPOWER_REQUISITION";
export const UPDATE_MANPOWER_REQUISITION = "UPDATE_MANPOWER_REQUISITION";
export const DELETE_MANPOWER_REQUISITION = "DELETE_MANPOWER_REQUISITION";

export const CREATE_DEGREE = "CREATE_DEGREE";
export const GET_DEGREE = "GET_DEGREE";
export const UPDATE_DEGREE = "UPDATE_DEGREE";
export const DELETE_DEGREE = "DELETE_DEGREE";

export const CREATE_ACCOUNT_TYPE = "CREATE_ACCOUNT_TYPE";
export const GET_ACCOUNT_TYPE = "GET_ACCOUNT_TYPE";
export const UPDATE_ACCOUNT_TYPE = "UPDATE_ACCOUNT_TYPE";
export const DELETE_ACCOUNT_TYPE = "DELETE_ACCOUNT_TYPE";

export const CREATE_GROUP_LEDGER = "CREATE_GROUP_LEDGER";
export const GET_GROUP_LEDGER = "GET_GROUP_LEDGER";
export const UPDATE_GROUP_LEDGER = "UPDATE_GROUP_LEDGER";
export const DELETE_GROUP_LEDGER = "DELETE_GROUP_LEDGER";
export const CATEGORY_SELECT_GROUP_LEDGER = "CATEGORY_SELECT_GROUP_LEDGER";

export const CREATE_SUB_GROUP_LEDGER = "CREATE_SUB_GROUP_LEDGER";
export const GET_SUB_GROUP_LEDGER = "GET_SUB_GROUP_LEDGER";
export const UPDATE_SUB_GROUP_LEDGER = "UPDATE_SUB_GROUP_LEDGER";
export const DELETE_SUB_GROUP_LEDGER = "DELETE_SUB_GROUP_LEDGER";
export const CATEGORY_SELECT_SUB_GROUP_LEDGER =
  "CATEGORY_SELECT_SUB_GROUP_LEDGER";

export const CREATE_CONTROL_LEDGER = "CREATE_CONTROL_LEDGER";
export const GET_CONTROL_LEDGER = "GET_CONTROL_LEDGER";
export const UPDATE_CONTROL_LEDGER = "UPDATE_CONTROL_LEDGER";
export const DELETE_CONTROL_LEDGER = "DELETE_CONTROL_LEDGER";
export const CATEGORY_SELECT_CONTROL_LEDGER = "CATEGORY_SELECT_CONTROL_LEDGER";

export const CREATE_ACCOUNT_LEDGER = "CREATE_ACCOUNT_LEDGER";
export const GET_ACCOUNT_LEDGER = "GET_ACCOUNT_LEDGER";
export const UPDATE_ACCOUNT_LEDGER = "UPDATE_ACCOUNT_LEDGER";
export const DELETE_ACCOUNT_LEDGER = "DELETE_ACCOUNT_LEDGER";

export const CREATE_SUPPLIER = "CREATE_SUPPLIER";
export const GET_SUPPLIER = "GET_SUPPLIER";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";

export const CREATE_BRANCH = "CREATE_BRANCH";
export const GET_BRANCH = "GET_BRANCH";
export const UPDATE_BRANCH = "UPDATE_BRANCH";
export const DELETE_BRANCH = "DELETE_BRANCH";

export const CREATE_BRAND = "CREATE_BRAND";
export const GET_BRAND = "GET_BRAND";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";

export const CREATE_MEASUREMENT_UNIT = "CREATE_MEASUREMENT_UNIT";
export const GET_MEASUREMENT_UNIT = "GET_MEASUREMENT_UNIT";
export const UPDATE_MEASUREMENT_UNIT = "UPDATE_MEASUREMENT_UNIT";
export const DELETE_MEASUREMENT_UNIT = "DELETE_MEASUREMENT_UNIT";

export const CREATE_CONDITION = "CREATE_CONDITION";
export const GET_CONDITION = "GET_CONDITION";
export const UPDATE_CONDITION = "UPDATE_CONDITION";
export const DELETE_CONDITION = "DELETE_CONDITION";

export const CREATE_PURCHASE_REQUISITION = "CREATE_PURCHASE_REQUISITION";
export const GET_PURCHASE_REQUISITION = "GET_PURCHASE_REQUISITION";
export const UPDATE_PURCHASE_REQUISITION = "UPDATE_PURCHASE_REQUISITION";
export const DELETE_PURCHASE_REQUISITION = "DELETE_PURCHASE_REQUISITION";


